### ISSUE TITLE
Troubles updating to 3.0.2

### ISSUE THREAD

**Issue by codyjames** [putyourlightson/craft-snaptcha#15]
### Describe the bug
I'm trying to update to the newest version of Snaptcha and am having issues. Even when I try to totally uninstall and re-install, it still is not working for me. One thing I'm noticing is that it doesn't have a Schema version in the project config file:

```
snaptcha:
  enabled: true
  licenseKey: XXX
  settings:
    allowList: ''
    denyList: ''
    errorButtonText: Resubmit
    errorJavascriptDisabled: 'JavaScript must be enabled for your submission to be verified. Please enable it and refresh the page.'
    errorMessage: 'For some reason your submission was flagged as spam. Please click the button below to resubmit your data.'
    errorTemplate: ''
    errorTitle: Error
    excludeControllerActions: ''
    expirationTime: '60'
    fieldName: snaptcha
    logRejected: '1'
    minimumSubmitTime: '1'
    oneTimeKey: ''
    salt: XXX
    validateUsers: '1'
    validationEnabled: '1'
```

### To reproduce
Steps to reproduce the behaviour:
1. Install snaptcha.
2. Try and use a form that has a snaptcha tag.
3. Get an error.

### Versions
- Plugin version: 3.0.2
- Craft version: 3.6.12
